# Generated by Django 3.1.4 on 2021-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_tasks_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Marked',
            field=models.BooleanField(default=False),
        ),
    ]
